### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by johnfelipe** [mitocw/moodle2edx#1]
Hi comunity, please tell me dump version moodle 1.9 or moodle 2.0

Tnks

**Comment by johnfelipe** [comment]
Hi again, please tell me steps for convert my moodle dump v2.0 to EDX
Tnks

**Comment by wildboardm** [comment]
Hello! When I run your script I get error:
`Converting moodle backup-moodle2-course2.mbz to edX /home/moodle/edx/
gzip: stdin has more than one entry--rest ignored
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "/usr/local/bin/moodle2edx", line 9, in <module>
    load_entry_point('moodle2edx==0.1.0', 'console_scripts', 'moodle2edx')()
  File "/home/moodle/src/moodle2edx/moodle2edx/main.py", line 551, in CommandLine
    clean_up_html=opts.clean_up_html,
  File "/home/moodle/src/moodle2edx/moodle2edx/main.py", line 66, in __init__
    qdict = self.load_questions(mdir,qfn)
  File "/home/moodle/src/moodle2edx/moodle2edx/main.py", line 449, in load_questions
    moodq = etree.parse('%s/%s' % (dir,qfn))
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:85131)
  File "src/lxml/parser.pxi", line 1782, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:124005)
  File "src/lxml/parser.pxi", line 1808, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:124374)
  File "src/lxml/parser.pxi", line 1712, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:123169)
  File "src/lxml/parser.pxi", line 1115, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:117533)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:110510)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:112276)
  File "src/lxml/parser.pxi", line 611, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:111078)
IOError: Error reading file '/tmp/moodle2edxs_RPEf/questions.xml': failed to load external entity "/tmp/moodle2edxs_RPEf/questions.xml"`

**Comment by pdpinch** [comment]
Sorry, this code isn't currently supported. 

Also, please don't hijack unrelated issues. If you start a new issue, and include the command you used that caused the stack trace, I may be able to give you some basic assistance.
